provider "hcloud" {
  token = local.effective_hcloud_token
}

provider "cloudflare" {
  api_token = local.effective_cloudflare_api_token
}

provider "tailscale" {
  oauth_client_id     = local.effective_tailscale_oauth_client_id
  oauth_client_secret = local.effective_tailscale_oauth_secret
  tailnet             = var.tailscale.tailnet
}


locals {
  talos_clusters = { for k, v in var.clusters : k => v if lookup(v, "type", "talos") == "talos" }
  gke_clusters   = { for k, v in var.clusters : k => v if lookup(v, "type", "talos") == "gke" }
  
  has_gcp_clusters = length([for k, v in var.clusters : k if try(v.gcp.project_id, "") != ""]) > 0
  has_gke_clusters = length(local.gke_clusters) > 0
  
  gcp_needed = coalesce(var.enable_gcp, local.has_gcp_clusters || local.has_gke_clusters)
  
  onepassword_needed = var.enable_onepassword && (
    var.hcloud_token == null ||
    var.cloudflare_api_token == null ||
    (var.tailscale.enabled && var.tailscale_oauth_secret == null) ||
    (var.tailscale.enabled && var.tailscale_oauth_client_id == null)
  )
  
  clustermesh_service_type = var.tailscale.enabled ? "NodePort" : "LoadBalancer"

  has_private_gke = anytrue([
    for name, cluster in var.clusters :
    try(cluster.gcp.enable_private_cluster, false)
    if try(cluster.type, "talos") == "gke"
  ])

  cilium_effective = merge(var.cilium, {
    encryption_enabled = coalesce(var.cilium.encryption_enabled, false)
    encryption_type    = var.cilium.encryption_type
    node_encryption    = var.cilium.node_encryption
  })
}

check "secrets_validation" {
  assert {
    condition     = var.enable_onepassword || var.hcloud_token != null
    error_message = "hcloud_token is required when enable_onepassword=false. Set it in secret.tfvars or via -var-file."
  }
  assert {
    condition     = var.enable_onepassword || var.cloudflare_api_token != null
    error_message = "cloudflare_api_token is required when enable_onepassword=false. Set it in secret.tfvars or via -var-file."
  }
  assert {
    condition     = var.enable_onepassword || !var.tailscale.enabled || var.tailscale_oauth_secret != null
    error_message = "tailscale_oauth_secret is required when enable_onepassword=false and tailscale.enabled=true."
  }
  assert {
    condition     = var.enable_onepassword || !var.tailscale.enabled || var.tailscale_oauth_client_id != null
    error_message = "tailscale_oauth_client_id is required when enable_onepassword=false and tailscale.enabled=true."
  }
}

# module "secrets" and effective_* locals are generated by terragrunt
# into secrets_optional.tf — see terragrunt.hcl

variable "hcloud_token" {
  description = "Hetzner Cloud API token"
  type        = string
  sensitive   = true
  default     = null
}

variable "cloudflare_api_token" {
  description = "Cloudflare API token"
  type        = string
  sensitive   = true
  default     = null
}

variable "tailscale_oauth_secret" {
  description = "Tailscale OAuth client secret"
  type        = string
  sensitive   = true
  default     = null
}

variable "tailscale_oauth_client_id" {
  description = "Tailscale OAuth client ID"
  type        = string
  sensitive   = true
  default     = null
}

variable "gcp_credentials" {
  description = "GCP service account credentials JSON (empty for ADC)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "cilium_version" {
  description = "Cilium Helm chart version (null = latest, must match across all clusters for ClusterMesh compatibility)"
  type        = string
  default     = null
}

data "http" "talos_latest_release" {
  count = var.talos_version == null ? 1 : 0
  url   = "https://api.github.com/repos/siderolabs/talos/releases/latest"
}

data "http" "kubelet_latest_release" {
  count = var.kubernetes_version == null ? 1 : 0
  url   = "https://api.github.com/repos/siderolabs/kubelet/releases/latest"
}

data "http" "cilium_latest_release" {
  count = var.cilium_version == null ? 1 : 0
  url   = "https://api.github.com/repos/cilium/cilium/releases/latest"
}

resource "terraform_data" "talos_version" {
  count = var.talos_version == null ? 1 : 0
  input = jsondecode(data.http.talos_latest_release[0].response_body).tag_name
  lifecycle {
    ignore_changes = [input]
  }
}

resource "terraform_data" "kubernetes_version" {
  count = var.kubernetes_version == null ? 1 : 0
  input = jsondecode(data.http.kubelet_latest_release[0].response_body).tag_name
  lifecycle {
    ignore_changes = [input]
  }
}

resource "terraform_data" "cilium_version" {
  count = var.cilium_version == null ? 1 : 0
  input = trimprefix(jsondecode(data.http.cilium_latest_release[0].response_body).tag_name, "v")
  lifecycle {
    ignore_changes = [input]
  }
}

locals {
  talos_version      = coalesce(var.talos_version, terraform_data.talos_version[0].input)
  kubernetes_version = coalesce(var.kubernetes_version, terraform_data.kubernetes_version[0].input)
  cilium_version     = coalesce(var.cilium_version, terraform_data.cilium_version[0].input)

  gcp_project_id = length([for k, v in var.clusters : v.gcp.project_id if try(v.gcp.project_id, "") != ""]) > 0 ? values(var.clusters)[0].gcp.project_id : null
  gcp_region     = length([for k, v in var.clusters : v.gcp.region if try(v.gcp.region, "") != ""]) > 0 ? values(var.clusters)[0].gcp.region : null
  gcp_zone       = length([for k, v in var.clusters : v.gcp.zone if try(v.gcp.zone, "") != ""]) > 0 ? values(var.clusters)[0].gcp.zone : null
}

resource "tls_private_key" "ssh" {
  algorithm = "ED25519"
}

resource "hcloud_network" "cluster" {
  for_each = { for k, v in local.cluster_hetzner_nodes : k => v if length(v.control_planes) > 0 || length(v.workers) > 0 }

  name     = "${each.key}-network"
  ip_range = "10.0.0.0/16"
  labels = {
    cluster    = each.key
    managed-by = each.key
  }
}

resource "hcloud_network_subnet" "cluster" {
  for_each = { for k, v in local.cluster_hetzner_nodes : k => v if length(v.control_planes) > 0 || length(v.workers) > 0 }

  network_id   = hcloud_network.cluster[each.key].id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = "10.0.0.0/16"
}

module "tailscale_key" {
  source = "./modules/tailscale"
  count  = var.tailscale.enabled ? 1 : 0

  create_key_only = true
  tag             = var.tailscale.tag
}

module "talos" {
  source   = "./modules/talos"
  for_each = local.talos_clusters

  cluster_name       = each.key
  cluster_id         = each.value.cluster_id
  talos_version      = local.talos_version
  kubernetes_version = local.kubernetes_version
  control_planes     = each.value.control_planes
  workers            = each.value.workers
  network            = var.network
  cilium             = local.cilium_effective
  cilium_version     = local.cilium_version

  tailscale_enabled  = var.tailscale.enabled
  tailscale_auth_key = var.tailscale.enabled ? module.tailscale_key[0].auth_key : ""
  tailscale_routes   = var.tailscale.enabled ? var.tailscale.routes : []

  dns_enabled = var.dns.enabled
  dns_domain  = var.dns.domain

  clustermesh_service_type = local.clustermesh_service_type

  hcloud_token = length([for cp in each.value.control_planes : cp if cp.provider == "hetzner"]) > 0 ? local.effective_hcloud_token : ""
  hcloud_network_id = length([for cp in each.value.control_planes : cp if cp.provider == "hetzner"]) > 0 ? hcloud_network.cluster[each.key].id : null

  hetzner_loadbalancer_enabled = var.hetzner.loadbalancer_enabled
}

locals {
  cluster_hetzner_nodes = {
    for k, v in local.talos_clusters : k => {
      control_planes = [for cp in v.control_planes : cp if cp.provider == "hetzner"]
      workers        = [for w in v.workers : w if w.provider == "hetzner"]
    }
  }

  cluster_gcp_nodes = {
    for k, v in local.talos_clusters : k => {
      control_planes = [for cp in v.control_planes : cp if cp.provider == "gcp"]
      workers        = [for w in v.workers : w if w.provider == "gcp"]
      gcp_config     = try(v.gcp, {})
    }
  }
}

module "hetzner" {
  source   = "./modules/providers/hetzner"
  for_each = { for k, v in local.cluster_hetzner_nodes : k => v if length(v.control_planes) > 0 || length(v.workers) > 0 }

  cluster_name          = each.key
  network_id            = hcloud_network.cluster[each.key].id
  control_planes        = each.value.control_planes
  workers               = each.value.workers
  ssh_public_key        = tls_private_key.ssh.public_key_openssh
  ssh_private_key       = tls_private_key.ssh.private_key_openssh
  talos_version         = local.talos_version
  hcloud_token          = local.effective_hcloud_token
  control_plane_configs = { for cp in each.value.control_planes : cp.name => module.talos[each.key].control_plane_configs[cp.name] }
  worker_configs        = { for w in each.value.workers : w.name => module.talos[each.key].worker_configs[w.name] }
}

locals {
  cluster_control_plane_ips = {
    for cluster_name, cluster in var.clusters : cluster_name => merge(
      length(lookup(local.cluster_hetzner_nodes, cluster_name, { control_planes = [], workers = [] }).control_planes) > 0 ? module.hetzner[cluster_name].control_plane_ips : {},
      lookup(local.gcp_cluster_control_plane_ips, cluster_name, {}),
      lookup(local.gke_clusters, cluster_name, null) != null ? { "${cluster_name}-gke" = lookup(local.gke_cluster_endpoints, cluster_name, "") } : {}
    )
  }

  cluster_worker_ips = {
    for cluster_name, cluster in var.clusters : cluster_name => merge(
      length(lookup(local.cluster_hetzner_nodes, cluster_name, { control_planes = [], workers = [] }).workers) > 0 ? module.hetzner[cluster_name].worker_ips : {},
      lookup(local.gcp_cluster_worker_ips, cluster_name, {})
    )
  }

  cluster_control_plane_ipv6s = {
    for cluster_name, cluster in var.clusters : cluster_name => merge(
      length(lookup(local.cluster_hetzner_nodes, cluster_name, { control_planes = [], workers = [] }).control_planes) > 0 ? module.hetzner[cluster_name].control_plane_ipv6s : {},
    )
  }

  cluster_worker_ipv6s = {
    for cluster_name, cluster in var.clusters : cluster_name => merge(
      length(lookup(local.cluster_hetzner_nodes, cluster_name, { control_planes = [], workers = [] }).workers) > 0 ? module.hetzner[cluster_name].worker_ipv6s : {},
    )
  }

  all_control_plane_ipv6s = merge(values(local.cluster_control_plane_ipv6s)...)
  all_worker_ipv6s        = merge(values(local.cluster_worker_ipv6s)...)

  cluster_install_complete = {
    for cluster_name, cluster in var.clusters : cluster_name => concat(
      length(lookup(local.cluster_hetzner_nodes, cluster_name, { control_planes = [], workers = [] }).control_planes) > 0 || length(lookup(local.cluster_hetzner_nodes, cluster_name, { control_planes = [], workers = [] }).workers) > 0 ? module.hetzner[cluster_name].install_complete : [],
      lookup(local.gcp_cluster_install_complete, cluster_name, []),
      lookup(local.gke_clusters, cluster_name, null) != null ? lookup(local.gke_cluster_install_complete, cluster_name, []) : []
    )
  }

  all_control_plane_ips   = merge(values(local.cluster_control_plane_ips)...)
  all_worker_ips          = merge(values(local.cluster_worker_ips)...)

  all_kubeconfigs = merge(
    { for k, v in local.talos_clusters : k => talos_cluster_kubeconfig.this[k].kubeconfig_raw },
    { for k, v in local.gke_clusters : k => lookup(local.gke_kubeconfigs, k, "") }
  )

  # First control plane Tailscale IP per cluster, for patching kubeconfig server URLs locally
  cluster_control_plane_tailscale_ips = var.tailscale.enabled ? {
    for cluster_name, cluster in var.clusters : cluster_name => (
      length(try(local.talos_clusters[cluster_name].control_planes, [])) > 0
      ? module.tailscale_devices[0].cluster_node_ips[cluster_name]["${cluster_name}-${local.talos_clusters[cluster_name].control_planes[0].name}"]
      : ""
    )
  } : {}
}

resource "talos_machine_bootstrap" "this" {
  for_each = { for k, v in local.talos_clusters : k => v if length(v.control_planes) > 0 }

  client_configuration = module.talos[each.key].client_configuration
  node                 = values(local.cluster_control_plane_ips[each.key])[0]
  endpoint             = values(local.cluster_control_plane_ips[each.key])[0]

  depends_on = [module.hetzner]
}

resource "talos_machine_configuration_apply" "control_plane" {
  for_each = merge([
    for cluster_name, cluster in local.talos_clusters : {
      for cp in cluster.control_planes : "${cluster_name}-${cp.name}" => {
        cluster_name = cluster_name
        node_name    = cp.name
        provider     = try(cp.provider, "")
      }
    }
  ]...)

  client_configuration        = module.talos[each.value.cluster_name].client_configuration
  machine_configuration_input = module.talos[each.value.cluster_name].control_plane_configs[each.value.node_name]
  node                        = local.cluster_control_plane_ips[each.value.cluster_name][each.value.node_name]
  endpoint                    = local.cluster_control_plane_ips[each.value.cluster_name][each.value.node_name]

  config_patches = each.value.provider == "hetzner" ? [
    jsonencode({
      machine = {
        kubelet = {
          extraArgs = {
            provider-id = module.hetzner[each.value.cluster_name].control_plane_provider_ids[each.value.node_name]
          }
        }
      }
    })
  ] : []

  depends_on = [talos_machine_bootstrap.this]
}

resource "talos_machine_configuration_apply" "worker" {
  for_each = merge([
    for cluster_name, cluster in local.talos_clusters : {
      for w in cluster.workers : "${cluster_name}-${w.name}" => {
        cluster_name = cluster_name
        node_name    = w.name
        provider     = try(w.provider, "")
      }
    }
  ]...)

  client_configuration        = module.talos[each.value.cluster_name].client_configuration
  machine_configuration_input = module.talos[each.value.cluster_name].worker_configs[each.value.node_name]
  node                        = local.cluster_worker_ips[each.value.cluster_name][each.value.node_name]
  endpoint                    = local.cluster_worker_ips[each.value.cluster_name][each.value.node_name]

  config_patches = each.value.provider == "hetzner" ? [
    jsonencode({
      machine = {
        kubelet = {
          extraArgs = {
            provider-id = module.hetzner[each.value.cluster_name].worker_provider_ids[each.value.node_name]
          }
        }
      }
    })
  ] : []

  depends_on = [talos_machine_configuration_apply.control_plane]
}

resource "talos_cluster_kubeconfig" "this" {
  for_each = { for k, v in local.talos_clusters : k => v if length(v.control_planes) > 0 }

  client_configuration = module.talos[each.key].client_configuration
  node                 = values(local.cluster_control_plane_ips[each.key])[0]
  endpoint             = values(local.cluster_control_plane_ips[each.key])[0]

  depends_on = [talos_machine_configuration_apply.control_plane]
}

data "talos_client_configuration" "this" {
  for_each = local.talos_clusters

  cluster_name         = each.key
  client_configuration = module.talos[each.key].client_configuration
  endpoints            = var.tailscale.enabled ? values(module.tailscale_devices[0].cluster_node_ips[each.key]) : values(local.cluster_control_plane_ips[each.key])
  nodes                = var.tailscale.enabled ? values(module.tailscale_devices[0].cluster_node_ips[each.key]) : concat(values(local.cluster_control_plane_ips[each.key]), values(local.cluster_worker_ips[each.key]))
}

module "k8s_cleanup" {
  source   = "./modules/k8s"
  for_each = local.talos_clusters

  cluster_name   = each.key
  workers        = each.value.workers
  control_planes = each.value.control_planes
  kubeconfig     = length(each.value.control_planes) > 0 ? talos_cluster_kubeconfig.this[each.key].kubeconfig_raw : ""
}

module "tailscale_devices" {
  source = "./modules/tailscale"
  count  = var.tailscale.enabled ? 1 : 0

  clusters            = { for k, v in local.talos_clusters : k => { control_planes = v.control_planes, workers = v.workers } }
  gke_clusters        = []
  cluster_install_complete = local.cluster_install_complete
  tag                 = var.tailscale.tag
  tailnet             = var.tailscale.tailnet
  oauth_client_id     = local.effective_tailscale_oauth_client_id
  oauth_client_secret = local.effective_tailscale_oauth_secret
  manage_acl          = var.tailscale.manage_acl
  acl_policy          = var.tailscale.acl_policy
}

module "dns" {
  source = "./modules/dns"
  count  = var.dns.enabled ? 1 : 0

  domain                  = var.dns.domain
  internal_domain         = var.dns.internal_domain
  cluster_names           = keys(var.clusters)
  cluster_control_plane_ips = local.cluster_control_plane_ips
  cluster_worker_ips      = local.cluster_worker_ips
  tailscale_ips           = var.tailscale.enabled ? module.tailscale_devices[0].all_node_ips : {}

  depends_on = [talos_machine_bootstrap.this]
}

module "clustermesh" {
  source = "./modules/clustermesh"
  count  = var.cilium.clustermesh && length(var.clusters) > 1 ? 1 : 0

  cluster_names                = keys(var.clusters)
  kubeconfigs                  = local.all_kubeconfigs
  control_plane_tailscale_ips  = local.cluster_control_plane_tailscale_ips

  depends_on = [
    talos_cluster_kubeconfig.this,
    talos_machine_configuration_apply.control_plane,
    module.dns
  ]
}

output "wireguard_warning" {
  value = local.has_private_gke && var.cilium.clustermesh ? "INFO: GKE private clusters detected. Cross-cluster WireGuard tunnels will not work for private GKE nodes (behind NAT). In-cluster encryption works normally. ClusterMesh will use mTLS for cross-cluster auth." : null
}
