apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cilium-kubelet-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kubelet-api-admin
subjects:
- kind: User
  name: apiserver-kubelet-client
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: kube-apiserver-kubelet-client
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cilium-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cilium-install
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium-install
  namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: helm-install-cilium
  namespace: kube-system
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: helm-install-cilium
    spec:
      restartPolicy: OnFailure
      tolerations:
        - operator: Exists
      serviceAccount: cilium-install
      serviceAccountName: cilium-install
      hostNetwork: true
      containers:
      - name: helm-install-cilium
        image: alpine:latest
        command:
          - sh
          - -c
          - |
            apk add --no-cache helm
            helm repo add cilium https://helm.cilium.io/
            helm repo update
            helm upgrade --install cilium cilium/cilium --namespace kube-system \
              --version ${cilium_ver} \
              --set cluster.id=${cluster_id} \
              --set cluster.name=${cluster_name} \
              --set gke.enabled=true \
              --set cni.binPath=/home/kubernetes/bin \
              --set ipv4NativeRoutingCIDR=${native_cidr} \
              --set cgroup.autoMount.enabled=false \
              --set cgroup.hostRoot=/sys/fs/cgroup \
              --set sysctlFix.enabled=false \
              --set hubble.enabled=true \
              --set hubble.relay.enabled=true \
              --set hubble.ui.enabled=true \
              ${encryption_flags} ${clustermesh_enabled} ${gateway_api_enabled}
